// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW44uWOw8p2Ha7toB7cVNdWrNf9a5pLEQ',
    appId: '1:317628344610:web:da31f9dee32081a14e1d7b',
    messagingSenderId: '317628344610',
    projectId: 'favourapp-b9929',
    authDomain: 'favourapp-b9929.firebaseapp.com',
    storageBucket: 'favourapp-b9929.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVAibBdv2oXPC_GLSccAeROd2H6BrIozY',
    appId: '1:317628344610:android:f59f2e8f0131d3654e1d7b',
    messagingSenderId: '317628344610',
    projectId: 'favourapp-b9929',
    storageBucket: 'favourapp-b9929.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGaFqR-V8YplL3rbnY8iAbmjWUgE5bSx8',
    appId: '1:317628344610:ios:07f93dad671411c44e1d7b',
    messagingSenderId: '317628344610',
    projectId: 'favourapp-b9929',
    storageBucket: 'favourapp-b9929.appspot.com',
    androidClientId: '317628344610-gnnh4q5g77bd1ft7mmjmnr7h6br7nrp7.apps.googleusercontent.com',
    iosClientId: '317628344610-vho74ln0tp877a523tdu8s6teu8i9kj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.f',
  );

}